name: Publish Runner Image

on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       type: string
  #       description: Version of the runner being installed
  #     rollover:
  #       type: boolean
  #       description: Rollover the release by adding -rN suffix (default false)

env:
  UPSTREAM: actions/runner
  LOCAL: ${{ github.repository}}

jobs:
  build:
    runs-on: self-hosted
    container: ubuntu:22.04
    steps:
    - name: Compute version
      id: version
      run: |
        find /runner || :
        echo "$PATH"
        env
        echo hello
        echo hello world
