on: push

jobs:
  test:
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - run: |
          echo $HOME
          pwd
          echo '-------------------------------------------------------------------'
          find
