on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $HOME
          id
          pwd
          echo '-------------------------------------------------------------------'
          rm -rf /home/runner/runners/2.314.1/bin/
          ls -la /home/runner/runners/
          ls -la /home/runner/runners/2.314.1/bin/ || :
          cat /proc/self/uid_map
          ps -A uxw
