on: push

jobs:
  test:
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - run: |
          pwd
          echo '-------------------------------------------------------------------'
          env
