on: push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: |
          id
          pwd
          echo '-------------------------------------------------------------------'
          find
