on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $HOME
          id
          pwd
          echo '-------------------------------------------------------------------'
          find $HOME
