on: push

jobs:
  test:
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - run: |
          pwd
          echo $HOME
          echo $PATH         
          echo '-------------------------------------------------------------------'
          env
          echo '-------------------------------------------------------------------'
          ls -l /etc/environment || :
          cat /etc/profile || :
